services:

  db:
    restart: always
    image: postgres
    
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.app

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

    depends_on:
      - db

#    command: sleep 9999

    # remove
    volumes:
      - ./app:/app
      
      - ./logs:/var/log/app/

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    
    depends_on:
      - app

    ports:
      - $NGINX_EXPOSED_ON:80

