apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer #ukloni kasnije da ne bi backend ne bi bio dostupan spolja
  selector:
    app: app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

