name: CI/CD Pipeline for EKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push frontend image
      run: |
        docker build -f Dockerfile.nginx -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}

    - name: Build and push backend image
      run: |
        docker build -f Dockerfile.app -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: eu-central-1
#
#    - name: Set up kubectl for EKS  #igor-app-cluster
#      run: |
#        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
#
#    - name: Update Kubernetes deployments
#      run: |
#        kubectl set image deployment/frontend-deployment frontend=${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
#        kubectl set image deployment/backend-deployment backend=${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
#
#
